In [1]:
# numpy, simplifid form of numerical python, is a library for working with arrays of data
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [2]:
my_arr= np.arange(1_000_000)
my_list= list(range(1_000_000))

In [3]:
%timeit for _ in range(10): my_arr2= my_arr*2
%timeit for _ in range(10): my_list2= [x*2 for x in my_list]

25.9 ms ± 1.76 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
606 ms ± 36.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
data= np.random.randn(2, 3)
data

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])

In [5]:
data*10
data+data

array([[-2.0471,  4.7894, -5.1944],
       [-5.5573, 19.6578, 13.9341]])

array([[-0.4094,  0.9579, -1.0389],
       [-1.1115,  3.9316,  2.7868]])

In [7]:
data.shape
data.dtype

(2, 3)

dtype('float64')